### ISSUE TITLE
jwt관련 보안 처리방안

### ISSUE THREAD

**Issue by Dongbok-Lee** [xenx96/cgt#11]
https://blog.ull.im/engineering/2019/02/07/jwt-strategy.html / 참고

토큰 만료시간 설정 => 짧은 만료기간은 자주 로그인을 해야하기에 불편함, 길면 탈취의 경우 위험함..

- Sliding session + access token 활용 =>접속이 주로 단발성으로 이루어지는 서비스의 경우 Sliding Sessions 전략의 효과가 크지 않다.

- access token + refresh token 활용 =>서버에 별도의 storage를 만들어야 한다. ,refresh token탈취시, 역시 위험함.

---
- 현재 재고해 볼 만한 부분
 IP정보를 토큰에 담아 현재 아이피 + 토큰정보 일치 할 경우 true(Sliding session or refresh토큰 추가해서 구현가능) --> 장단점 확인해보기

**Comment by Dongbok-Lee** [comment]
jwt토큰 저장소 위치에 따른 보안 취약점
-local storage: XSS공격에 취약
-session storage: 창이종료되면 바로 토큰 만료(권장 x)
-cookie: csrf공격에 취약

각 취약점 장점 단점 대응점 
https://doqtqu.tistory.com/277 참고

**Comment by Dongbok-Lee** [comment]
https://velog.io/@dudtjr913/XSS
local storage: xss공격에 취약 하지만 리액트가 inner HTML방식이 아니므로 안전 하지만 <a>나 <href>같은 공격이 가능할 듯 또한, 값 내부 검증으로 인해 어느정도 예방이가능

cookie: 구현과 예방이 local storage보다 까다로움, HTTPonly를 통해 XSS공격을 예방할수 있다. 하지만 CSRF공격 에취약, XSS공격보다는 치명적이지 않다는 장점이 있음.

결론: 게시판내에서 <a> 나 <href> 같은 태그를 필요로 하지 않는다면 local storage가 좀 더 나은 결정인듯 싶다. 구현 또한 간단. 하지만 리액트를 사용하는것이 아니거나 <a>태그를 포함시킨다면 cookie를 사용하는 쪽이 보안쪽으로 좀 더 옳은 선택인듯..

**Comment by xenx96** [comment]
1.간접 HTTPS통신을 JAVA로 구현하여 JWT와 HTTPS를 사용하는 것이 OAuth 2.0 + HTTPS만큼은 아니더라도 괜찮은 방법인 듯 하다.
2.JWT에 IP연결하여 2중조회 방법은 불필요한 정보 및 불필요한 조회로 인하여, 좋지 못한 방법이라고 함.
3. 따라서 HTTPS에 OAuth2.0을 연결하는 방법을 찾거나, JWT에 HTTPS를 이용한다.
4. Java에서 임시HTTPS 구현시 문제점 : 인증되지않은 사이트 라는 경고문구 발생 가능( 하지만 문제는 없음)

**Comment by xenx96** [comment]
> https://blog.ull.im/engineering/2019/02/07/jwt-strategy.html / 참고
> 
> 토큰 만료시간 설정 => 짧은 만료기간은 자주 로그인을 해야하기에 불편함, 길면 탈취의 경우 위험함..
> 
> * Sliding session + access token 활용 =>접속이 주로 단발성으로 이루어지는 서비스의 경우 Sliding Sessions 전략의 효과가 크지 않다.
> * access token + refresh token 활용 =>서버에 별도의 storage를 만들어야 한다. ,refresh token탈취시, 역시 위험함.
> 
> * 현재 재고해 볼 만한 부분
>   IP정보를 토큰에 담아 현재 아이피 + 토큰정보 일치 할 경우 true(Sliding session or refresh토큰 추가해서 구현가능) --> 장단점 확인해보기
